# -*- coding: utf-8 -*-
"""PCA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rDMyCXy6VHq1cgL7Q2LjF9oALVmdfOan
"""

import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

X = pd.read_csv('cars.csv')
X = X.iloc[:, :-1]
X = X.apply(pd.to_numeric, errors='coerce', axis=1)
X = X.dropna().values
min_max = MinMaxScaler()
X = min_max.fit_transform(X)

pca = PCA(n_components=None)
X = pca.fit_transform(X)
print(pca.explained_variance_ratio_)



U, S, V = np.linalg.svd(X)
print(U.shape)

print(V.shape
     )

s = S[0:8].sum()
print(s)

ss = S.sum()
print(ss)

ss = S.sum()
sss = []
for i in range(1, 8):
  s = S[0:i].sum()
  sss.append(s/ss)
  if s/ss > 0.90:
    s_2 = s/ss
    break
    
print(s_2)
print(sss)

np.argmax(sss)

import tensorflow as tf

# Import MINST data
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("/tmp/data/", one_hot=True)

batch_xs, batch_ys = mnist.train.next_batch(batch_size=10)
print(batch_ys)

